name: Run OPA Tests
on: [push]
jobs:
  Run-OPA-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: latest

    - name: Run OPA Tests
      # run: opa exec --decision terraform/analysis/authz --bundle policies/ plan.json
      # run: opa eval -i plan.json -d policies/ data.enforce_policies.allow | jq
      # shell: bash
      run: | 
        # opa eval --input plan.json --data policies/ data.enforce_policies.allow

        # Prevent GitHub Action from exiting early
        set +e pipefail

        # Check if the Variable representing all applicable Rules is true/false
        opa eval --input plan.json --data policies/ data.enforce_policies.allow | jq '.result[0].expressions[0].value' --raw-output --exit-status &>/dev/null
        OPA_EVALUATION="$?"

        # If the evaluation fails, provide more information to explain why
        if [ "$OPA_EVALUATION -ne 0 ]; then
          echo "Terraform plan violates provided Open Policy Agent policies."
          exit $OPA_EVALUATION
        else
          echo "Terraform plan passes provided Open Policy Agent policies."
        fi
